<div id="ve_element-ve_row-control">
    <div class="ve_controls row-controls">
        <div class="inner">
            <span class="control-item element-name">Row</span>
            <span class="control-item element-move"><i class="fa fa-arrows"></i></span>
            <a class="control-item" title="edit" data-cmd="edit"><i class="fa fa-pencil"></i></a>
            <a class="control-item" title="duplicate" data-cmd="duplicate"><i class="fa fa-files-o"></i></a>
            <a class="control-item" title="delete" data-cmd="delete"><i class="fa fa-trash"></i></a>
        </div>
    </div>
</div>
<div id="ve_element-ve_col-control">
    <div class="ve_controls col-controls">
        <div class="inner">
            <span class="control-item element-name">Col (<span class="element-width"></span>/12)</span>
            <span class="control-item element-move"><i class="fa fa-arrows"></i></span>
            <a class="control-item" title="edit" data-cmd="edit"><i class="fa fa-pencil"></i></a>
            <a class="control-item" title="duplicate" data-cmd="duplicate"><i class="fa fa-files-o"></i></a>
            <a class="control-item" title="delete" data-cmd="delete"><i class="fa fa-trash"></i></a>
        </div>
    </div>
</div>
<script type="text/html" id="ve_element-default-control">
    <div class="ve_controls element-controls">
        <div class="inner">
            <span class="control-item element-name" title="<%= title %>"><%= name %></span>
            <span class="control-item element-move"><i class="fa fa-arrows"></i></span>
            <a class="control-item" title="edit" data-cmd="edit"><i class="fa fa-pencil"></i></a>
            <a class="control-item" title="duplicate" data-cmd="duplicate"><i class="fa fa-files-o"></i></a>
            <a class="control-item" title="delete" data-cmd="delete"><i class="fa fa-trash"></i></a>
        </div>
    </div>
</script>