<?php
/**
 * @var VE_Editor $editor
 */
?>
<div id="ve-topbar">
    <div class="ve-center">
        <?php echo $editor->getPostType();?>
    </div>
    <div class="ve-logo">
        <img src="<?php echo VE_URL.'/view/images/logo.png'?>" />
    </div>
    <ul class="panel-items-control">
        <li class="elements-filter">
            <a href="#" data-show-item="panel-item-1">Widgets <i class="fa fa-angle-down"></i></a>
            <ul class="submenu">
                <li><a data-filter="all" href="#"> All </a></li>
                <li><a data-filter="most-used" href="#"> Most used </a></li>
                <li><a data-filter="custom" href="#"> Custom </a></li>
                <li><a data-filter="media" href="#"> Media </a></li>
            </ul>
        </li>
        <li>
            <a href="#" data-show-item><?php echo $editor->getPostType();?> Setting <i class="fa fa-angle-down"></i></a>
            <ul class="submenu">
                <?php
                echo '<li>';
                $this->render('panel/page-settings');
                echo '</li>';
                ?>
            </ul>

        </li>
    </ul>
    <div class="ve-screensize">
        <label><input type="text" name="screensize" id="screensize" value=""/>px</label>
    </div>

    <div class="ve-right ve-buttons">
        <ul class="panel-items-control">
            <li>
                <a id="toggle-mode" class="vebtn">Grid Off</a>
            </li>
<!--
            <li>
                <a href="#" data-show-item>Save As <i class="fa fa-angle-down"></i></a>
                <ul class="submenu">
                    <?php if(!$editor->isTemplate()){?>
                        <li><?php $this->render('topbar/save-template');?></li>
                    <?php }?>
                    <?php if(!$editor->isElement()){?>
                        <li><?php $this->render('topbar/custom-element');?></li>
                    <?php }?>
                </ul>
-->
            </li>

            <li>
                <a href="#" data-show-item>Save <i class="fa fa-angle-down"></i></a>
                <ul class="submenu">
                    <li><a id="update-post">Draft</a></li>
                    <li><a id="publish-post">Publish</a></li>
                    <?php if(!$editor->isWidget() && !$editor->isPopup()) {?>
                    <li><a id="view_post_link" href="<?php echo get_permalink($editor->post_id);?>">View</a></li>
                    <?php }?>
                </ul>

            </li>
            <li>
                <a href="#" data-show-item>New <i class="fa fa-angle-down"></i></a>
                <ul class="submenu">

                    <li><a  href="<?php echo admin_url("edit.php?ve_action=ve_inline&post_id=new&post_type=page");?>">Page</a></li>
                </ul>

            </li>
            <li>
                <a href="#" data-show-item>Edit <i class="fa fa-angle-down"></i></a>
                <ul class="submenu">
                    <li><?php $this->render('panel/page-listing');?></li>

                </ul>

            </li>
            <li><a href="<?php echo admin_url();?>" class="vebtn">Exit</a></li>
        </ul>


    </div>
</div>