<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */

?>
<a href="#TB_inline?width=300&height=200&inlineId=ve-save-template" title="Save as Template" class="thickbox">Template</a>
<div id="ve-save-template" class="hidden">
    <form class="ve-ajax-form ve-dialog" action="" data-message="Template saved!">
        <input type="hidden" name="action" value="ve_save_as_template"/>
        <input type="hidden" name="from_page" value="<?php echo $editor->getPost()->ID;?>"/>
        <div style="padding:10px">
            <label>Title:</label>
            <input class="widefat" name="post_title" value="<?php echo esc_attr($editor->getPost()->post_title);?>" type="text"/>
            <p class="form-control submit">
                <input type="submit" value="Save" class="save"/>
            </p>
        </div>
    </form>
    <div class="ve_clearfix"></div>
</div>