<div id="mce-ve-widget" class="mce-ve-dialog" style="display: none;">
    <form class="mce-ve-form">
        <div class="ve-dialog-title">
            <?php _e( 'Insert Widget' ) ?>
            <button type="button" class="mce-ve-dialog-close"><span class="screen-reader-text"><?php _e( 'Close' ); ?></span></button>
        </div>
    </form>
</div>
<div id="mce-ve-popup" class="mce-ve-dialog" style="display: none">
    <form class="mce-ve-form">
        <div class="ve-dialog-title">
            <?php _e( 'Insert Popup' ) ?>
            <button type="button" class="mce-ve-dialog-close"><span class="screen-reader-text"><?php _e( 'Close' ); ?></span></button>
        </div>
        <div class="mce-ve-options">

        </div>
        <div class="submitbox">
            <div class="mce-ve-cancel">
                <a class="submitdelete deletion" href="#"><?php _e( 'Cancel' ); ?></a>
            </div>
            <div class="mce-ve-update">
                <input type="submit" value="<?php esc_attr_e( 'Add Popup' ); ?>" class="button button-primary" name="mce-ve-submit">
            </div>
        </div>
    </form>
</div>