<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */

?>
<a href="#TB_inline?width=600&height=550&inlineId=ve-page-settings" title="Page Settings" class="thickbox">Page Setting</a>
<div id="ve-page-settings" class="hidden">
    <form class="ve-ajax-form ui-tabs pure-form" data-update-values="1" action="">
        <div class="ve-ui-tabs">
            <ul>
                <li><a href="#page-setting-tab1">Setting</a></li>
                <li><a href="#page-setting-tab2">Style</a></li>
            </ul>
            <div class="ui-tabs-panel" id="page-setting-tab1">
                <p>
                    <label for="ve_post_title">Title:</label>
                    <input class="widefat" id="ve_post_title" type="text" name="post_title" value="<?php echo esc_attr($editor->post->post_title);?>"/>
                </p>
                <p>
                    <label for="ve_post_slug">Slug:</label>
                    <input class="widefat" id="ve_post_slug" type="text" name="post_name" value="<?php echo esc_attr($editor->post->post_name);?>"/>
                </p>
                <p>
                    <label for="ve_post_slug">Meta Description:</label>
                    <br />
                    <textarea class="widefat" name="metas[post_description]"><?php echo @esc_attr($editor->post->metas['post_description']);?></textarea>
                </p>
                <p>
                    <label for="ve_post_slug">Meta tags:</label>
                    <br />
                    <textarea class="widefat" name="metas[post_tags]"><?php echo @esc_attr($editor->post->metas['post_tags']);?></textarea>
                </p>
            </div>
            <div id="page-setting-tab2">

            </div>
        </div>

        <input type="hidden" name="action" value="ve_update_post"/>

        <p class="form-control submit">
            <input type="submit" value="Update" class="save"/>
        </p>

    </form>
    <div class="ve_clearfix"></div>
</div>