<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */
$post=$editor->getPost();

$positionOptions=array(
    'center'=>'Center',
    'top-left'=>'Top left',
    'top-right'=>'Top Right',
    'bottom-left'=>'Bottom left',
    'bottom-right'=>'Bottom Right'
);
$appearanceOptions=array(
    ''=>'Default',
    'center'=>'Center',
);
$placementOptions=array(
    ''=>'None',
    'all'=>'Whole site',
    'post'=>'All posts',
    'page'=>'All pages',
    'category'=>'By Category',

);
$openOptions=array(
    ''=>'Not open automatically',
    'open_on_mouse_out'=>'Open when mouse out of page',
    'open_with_delay'=>'Open after page loaded',
);
?>
<a href="#TB_inline?width=600&height=550&inlineId=ve-popup-settings" title="Popup Settings" class="thickbox">Popup Setting</a>
<div id="ve-popup-settings" class="hidden">
    <form class="ve-ajax-form ve-popup-settings ui-tabs" data-update-values="1">
        <input type="hidden" name="action" value="ve_update_post_meta"/>
        <ul role="tablist" class="ui-tabs-nav ui-helper-reset ui-helper-clearfix ui-widget-header ui-corner-all">
            <li aria-expanded="true" aria-selected="true" aria-labelledby="ui-id-7" aria-controls="ve-element-primary-feature" tabindex="0" role="tab" class="ui-state-default ui-corner-top ui-tabs-active ui-state-active"><a id="ui-id-7" tabindex="-1" role="presentation" class="ui-tabs-anchor" href="#ve-element-primary-feature">Setting</a></li>
        </ul>
        <div class="ui-tabs-panel">
            <p>
                <label for="ve_post_title">Popup Title:</label>
                <input class="widefat" id="ve_post_title" type="text" name="post_title" value="<?php echo esc_attr($editor->post->post_title);?>"/>
            </p>
        <p class="ve_row">
            <label for="position" class="ve_col-sm-3">Popup Position:</label>
            <select name="position" id="position" class="ve_col-sm-3">
                <?php foreach($positionOptions as $value=>$title){
                    printf('<option value="%s"%s>%s</option>',$value,selected($value,$post->position,false),$title);
                }?>
            </select>

        </p>

        <p class="small-input" data-show-if="appearance" data-show-value="center" data-compare="!=">
            <strong>Offset:</strong><br/>

            <label for="top">Top:</label>
            <input class="" type="text" name="top" value="<?php echo esc_attr($post->top);?>">

            <label for="left">Left:</label>
            <input type="text" name="left" value="<?php echo esc_attr($post->left);?>">

            <label for="bottom">Bottom:</label>
            <input type="text" name="bottom" value="<?php echo esc_attr($post->bottom);?>">

            <label for="right">Right:</label>
            <input type="text" name="right" value="<?php echo esc_attr($post->right);?>">
            <span class="clearfix"></span>
        </p>
        <p  class="ve_row">
            <label for="placement" class="ve_col-sm-3">Placement:</label>
            <select name="placement" id="placement" class="ve_col-sm-3">
                <?php foreach($placementOptions as $value=>$title){
                    printf('<option value="%s"%s>%s</option>',$value,selected($value,$post->placement,false),$title);
                }?>
            </select>

        </p>
        <div class="ve_row" data-show-if="placement" data-show-value="category">
            <div class="ve_col-sm-12">
                <label for="popup_category">Category:</label><br>
                <select id="popup_category" multiple="multiple" name="popup_category[]">
                    <?php
                        $categories=get_categories();
                        foreach($categories as $category){
                            printf('<option value="%s"%s>%s</option>',$category->term_id,selected(in_array($category->term_id,(array)$post->popup_category),true,false),$category->cat_name.' ('.$category->category_count.')');
                        }
                    ?>
                </select>
                <script type="text/javascript">
                    jQuery("#popup_category").select2({
                        width:"360"



                    });
                </script>
            </div>
        </div>

        <div class="ve_row" data-show-if="placement" data-show-value="post">
            <div class="ve_col-sm-12">
                <label for="popup_post">Post(limit to some post if you want):</label><br>
                <select id="popup_post" multiple="multiple" name="popup_post[]">
                    <?php if($post->popup_post){
                        foreach($post->popup_post as $post_id){
                            $post=get_post($post_id);
                            printf('<option value="%s" selected="selected">%s</option>',$post_id,$post->post_title);
                        }
                    }?>
                </select>
                <script type="text/javascript">
                    jQuery("#popup_post").select2({
                        width:"360",
                        ajax: {
                            url: ajaxurl,
                            dataType: 'json',
                            delay: 250,
                            data: function (params) {
                                return {
                                    q: params.term, // search term
                                    page: params.page,
                                    action:'ve_suggest',
                                    type:'post'
                                };
                            },
                            processResults: function (data, page) {
                                // parse the results into the format expected by Select2.
                                // since we are using custom formatting functions we do not need to
                                // alter the remote JSON data
                                return {
                                    results: data
                                };
                            },
                            cache: true
                        },
                        minimumInputLength: 1



                    });
                </script>
            </div>
        </div>

        <div class="ve_row" data-show-if="placement" data-show-value="page">
            <div class="ve_col-sm-12">
                <label for="popup_page">Page(limit to some page if you want):</label><br>
                <select id="popup_page" multiple="multiple" name="popup_page[]">
                    <?php if($post->popup_page){
                        foreach($post->popup_page as $post_id){
                            $post=get_post($post_id);
                            printf('<option value="%s" selected="selected">%s</option>',$post_id,$post->post_title);
                        }
                    }?>
                </select>
                <script type="text/javascript">
                    jQuery("#popup_page").select2({
                        width:"360",
                        ajax: {
                            url: ajaxurl,
                            dataType: 'json',
                            delay: 250,
                            data: function (params) {
                                return {
                                    q: params.term, // search term
                                    page: params.page,
                                    action:'ve_suggest',
                                    type:'page'
                                };
                            },
                            processResults: function (data, page) {
                                // parse the results into the format expected by Select2.
                                // since we are using custom formatting functions we do not need to
                                // alter the remote JSON data
                                return {
                                    results: data
                                };
                            },
                            cache: true
                        },
                        minimumInputLength: 1



                    });
                </script>
            </div>
        </div>


        <span class="clearfix"></span>


        <span class="clearfix"></span>
        <p class="ve_row">
            <label for="open" class="ve_col-sm-4">Popup Open:</label>
            <select name="open" id="open" class="ve_col-sm-4">
                <?php foreach($openOptions as $value=>$title){
                    printf('<option value="%s"%s>%s</option>',$value,selected($value,$post->open,false),$title);
                }?>
            </select>

        </p>
        <div class="ve_row" data-show-if="open" data-show-value="open_with_delay">
            <label class="ve_col-sm-4" for="delay">Delay timer(in second):</label>
            <input class="ve_col-sm-4" type="number" name="delay" id="delay" value="<?php echo absint($post->delay);?>"/>
        </div>
            </div>
        <p class="form-control submit">
            <input type="submit" value="Update" class="save"/>
        </p>

    </form>
</div>