<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */
$post=$editor->getPost();

$positionOptions=array(
    'center'=>'Center',
    'top-left'=>'Top left',
    'top-right'=>'Top Right',
    'bottom-left'=>'Bottom left',
    'bottom-right'=>'Bottom Right'
);
$appearanceOptions=array(
    ''=>'Default',
    'center'=>'Center',
);
$placementOptions=array(
    ''=>'None',
    'all'=>'Whole site',
    'post'=>'All posts',
    'page'=>'All pages',
    'category'=>'By Category',

);
$openOptions=array(
    ''=>'Not open automatically',
    'open_on_mouse_out'=>'Open when mouse out of page',
    'open_with_delay'=>'Open after page loaded',
);
$getBackgroundStyleOptions=function ($current_value) {
    $output = '<option value="">' . __( 'Theme defaults', 'visual_editor' ) . '</option>';
    $styles = array(
        __( "Cover", 'visual_editor' ) => 'cover',
        __( 'Contain', 'visual_editor' ) => 'contain',
        __( 'No Repeat', 'visual_editor' ) => 'no-repeat',
        __( 'Repeat', 'visual_editor' ) => 'repeat'
    );
    foreach ( $styles as $name => $style ) {
        $output .= '<option value="' . $style . '"'.selected($style,$current_value,false).'>' . $name . '</option>';
    }
    return $output;
};
$poptions = get_post_meta($post->ID,'_ve_poptions',true);
        if(!is_array($poptions))
        {
            $poptions = array();
        }
?>
<a href="#TB_inline?width=600&height=550&inlineId=ve-popup-settings" title="Popup Settings" class="thickbox">Popup Setting</a>
<div id="ve-popup-settings" class="hidden">
    <form class="ve-ajax-form ve-popup-settings" data-update-values="1">
        <input type="hidden" name="action" value="ve_update_post_meta"/>
        <div class="ve-ui-tabs">
            <ul>
                <li><a href="#popup-setting-tab1">Setting</a></li>
                <li><a href="#popup-setting-tab2">Style</a></li>
            </ul>

            <div id="popup-setting-tab1" class="ui-tabs-panel">
                <p>
                    <label for="ve_post_title">Popup Title:</label>
                    <input class="widefat" id="ve_post_title" type="text" name="post_title" value="<?php echo esc_attr($editor->post->post_title);?>"/>
                </p>
                <p class="ve_row">
                    <label for="position" class="ve_col-sm-3">Popup Options:</label>
                </p>
                <p class="">
                <?php foreach($poptions as $option){
                    $str = $positionOptions[$option['position']] . "_";
                    $str .= $placementOptions[$option['placement']] . "_";
                    $str .= $openOptions[$option['open']] ;
                    ?>

                       <strong><?php echo $str;?></strong><br/>

                <?php } ?>
                </p>


            </div>
            <div id="popup-setting-tab2" class="">
                <?php $img_ids=$post->background_image;?>
                <h2>Overlay:</h2>
                <div class="ve_row">
                    <div class="ve_col-sm-12">

                    </div>
                    <div class="ve_col-sm-4">
                        <label>Background:</label>
                        <div class="color-group">
                            <input type="text" name="background_color" value="<?php echo $post->background_color;?>" class="ve_color-control">
                        </div>
                    </div>

                    <div class="ve_col-sm-4">
                        <label>Opacity</label>
                        <div>
                            <input type="number" step="0.01" name="background_opacity" value="<?php echo $post->background_opacity;?>">
                        </div>
                    </div>
                </div>
                <div class="ve_row">
                    <div class="ve_col-sm-4">
                        <div class="ve_input_block">
                            <input type="hidden" class="ve-media-selected-images-ids" name="background_image" value="<?php echo $img_ids;?>"/>
                            <div class="ve-media-selected-images">
                                <ul class="ve-media-selected-images-list">
                                    <?php echo fieldAttachedImages(explode(',',$img_ids));?>
                                </ul>
                            </div>
                            <a class="ve-media-add-images-btn" href="#" title="Add image">Add image</a>
                        </div>
                    </div>
                    <div class="ve_col-sm-6">
                        <div class="ve_background-style" style="margin-top: 20px">
                            <select name="background_style" class="ve_background-style">
                                <?php
                                echo $getBackgroundStyleOptions($post->background_style);
                                ?>
                            </select>
                        </div>
                    </div>
                </div>


                <?php
                    $close_btn_styles=array(
                        'fa-times'=>'times',
                        'fa-times-circle '=>'times circle',
                        'fa-times-circle-o'=>'times circle o',

                    );
                    for($i=3;$i<=17;$i++){
                        if($i==9){
                            continue;
                        }
                        if($i<10){
                            $i='0'.$i;
                        }
                        $close_btn_styles['close-btn-icon-'.$i]='btn '.$i;
                    }
                    $close_btn_positions=array(
                        'right'=>'Right',
                        'left'=>'Left',
                    );
                ?>
                <h2>Close button:</h2>
                <div class="ve_row">
                    <div class="ve_col-sm-4">
                        <label for="popup-close-btn-style">Button Style:</label>
                    </div>
                    <div class="ve_col-sm-6">
                        <select id="popup-close-btn-style" name="close_btn_style">
                            <?php
                            $close_btn_style=$post->close_btn_style;
                            foreach($close_btn_styles as $o_value=>$o_title){
                                printf('<option value="%s"%s>%s</option>',$o_value,selected($close_btn_style,$o_value,false),$o_title);
                            }?>
                        </select>
                        <script type="application/javascript">
                            (function($) {
                                var formatState=function (state) {
                                    if (!state.id) {
                                        return state.text;
                                    }
                                    var $state = $(
                                        '<span><i class="fa ' + state.element.value.toLowerCase() + '"></i> ' + state.text + '</span>'
                                    );
                                    return $state;
                                };
                                $("#popup-close-btn-style").select2({
                                    width:300,
                                    templateResult: formatState,
                                    templateSelection: formatState
                                });
                            })(jQuery);
                        </script>
                    </div>
                </div>
                <div class="ve_row">
                    <div class="ve_col-sm-4">
                        <label>Position:</label>
                    </div>
                    <div class="ve_col-sm-4">
                        <select name="close_btn_position">
                            <?php
                                $close_btn_position=$post->close_btn_position;
                                if(!$close_btn_position){
                                    $close_btn_position='right';
                                }
                                foreach($close_btn_positions as $o_value=>$o_title){
                                    printf('<option value="%s"%s>%s</option>',$o_value,selected($o_value,$close_btn_position,false),$o_title);
                                }
                            ?>
                        </select>
                    </div>
                </div>
                <p class="small-input">
                    <strong>Offset:</strong><br/>

                    <label for="top">Top:</label>
                    <input class="" type="text" name="close_btn_top" value="<?php echo esc_attr($post->close_btn_top);?>">

                    <label for="left">Left:</label>
                    <input type="text" name="close_btn_left" value="<?php echo esc_attr($post->close_btn_left);?>">

                    <label for="bottom">Bottom:</label>
                    <input type="text" name="close_btn_bottom" value="<?php echo esc_attr($post->close_btn_bottom);?>">

                    <label for="right">Right:</label>
                    <input type="text" name="close_btn_right" value="<?php echo esc_attr($post->close_btn_right);?>">
                    <span class="clearfix"></span>
                </p>
            </div>
        </div>

        <p class="form-control submit">
            <input type="submit" value="Update" class="save"/>
        </p>


    </form>
</div>