<?php
/**
 * @var VE_Editor $editor
 * @var VE_View_Manager $this
 */
$post=$editor->getPost();

$positionOptions=array(
    'top'=>'Top of page',
    'bottom'=>'Bottom',
    'after'=>'After x paragraph',
);
$appearanceOptions=array(
    ''=>'Default',
    'left'=>'Left',
    'right'=>'Right',
    'center'=>'Center',
);
$placementOptions=array(
    ''=>'None',
    'post'=>'All posts',
    'page'=>'All pages',
    'category'=>'By Category',

);

?>
